import type { Metadata } from 'next';

import { Box, ThemeProvider } from '@mui/material';

import Logo from './components/logo';
import { GameEventsProvider } from './contexts/GameEventsContext';
import './globals.css';
import theme from './theme';

// adjust path if needed

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={theme}>
          <GameEventsProvider>
            <Logo />
            {/* Main content with top padding to avoid logo overlap */}
            <Box
              sx={{
                paddingLeft: 0,
                paddingRight: 0,
                margin: 0,
                overflowX: 'hidden', // prevent scrollbar caused by logo
              }}
            >
              {children}
            </Box>
          </GameEventsProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
